<x-filament-panels::page>
    <div class="grid grid-cols-1 lg:grid-cols-12 gap-6">

        <!-- Sidebar: Batches History -->
        <div class="lg:col-span-3 xl:col-span-2 space-y-6">
            <x-filament::section>
                <x-slot name="heading">
                    Generate New Batch
                </x-slot>

                <form wire:submit.prevent="generateBatch" class="space-y-4">
                    <div>
                        <label class="text-xs font-bold uppercase tracking-wider text-gray-500 block mb-1">Start Date</label>
                        <input type="date" wire:model.defer="startDate" class="w-full text-sm rounded-lg border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-900 dark:text-white shadow-sm focus:border-indigo-500 focus:ring-indigo-500" required>
                    </div>

                    <div>
                        <label class="text-xs font-bold uppercase tracking-wider text-gray-500 block mb-1">End Date</label>
                        <input type="date" wire:model.defer="endDate" class="w-full text-sm rounded-lg border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-900 dark:text-white shadow-sm focus:border-indigo-500 focus:ring-indigo-500" required>
                    </div>

                    <x-filament::button type="submit" class="w-full" size="md" icon="heroicon-m-plus-circle">
                        Generate Batch
                    </x-filament::button>
                </form>
            </x-filament::section>

            <x-filament::section>
                <x-slot name="heading">
                    Batch History
                </x-slot>

                <div class="space-y-3 max-h-[400px] overflow-y-auto custom-modal-scrollbar">
                    @forelse($this->batches as $b)
                    <button wire:click="selectBatch({{ $b->id }})"
                        class="w-full text-left p-3 rounded-xl border transition {{ $this->activeBatchId === $b->id ? 'bg-indigo-50/50 border-indigo-200 dark:bg-indigo-950/20 dark:border-indigo-800/40' : 'bg-white dark:bg-gray-900 border-gray-200 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-white/5' }}">
                        <div class="flex justify-between items-center mb-1">
                            <span class="font-bold text-xs text-gray-400">#{{ $b->id }}</span>
                            <x-filament::badge
                                color="{{ $b->status === 'draft' ? 'warning' : ($b->status === 'approved' ? 'success' : 'info') }}"
                                size="sm">
                                {{ ucfirst($b->status) }}
                            </x-filament::badge>
                        </div>
                        <div class="text-sm font-semibold text-gray-800 dark:text-gray-200">
                            {{ $b->start_date->format('M d') }} - {{ $b->end_date->format('M d, Y') }}
                        </div>
                        <div class="text-[10px] text-gray-500 mt-1">
                            By {{ $b->generatedBy->name }}
                        </div>
                    </button>
                    @empty
                    <div class="text-center py-6 text-gray-500 text-sm">
                        No batches generated yet.
                    </div>
                    @endforelse
                </div>
            </x-filament::section>
        </div>

        <!-- Main Panel: Selected Batch Review -->
        <div class="lg:col-span-9 xl:col-span-10 space-y-6">
            @if($this->activeBatch)
            @php
            $batch = $this->activeBatch;
            @endphp

            <!-- Card 1: Batch Info & Workflow Actions -->
            <x-filament::section>
                <!-- Header -->
                <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 border-b border-gray-100 dark:border-gray-800 pb-4 mb-6">
                    <div>
                        <h2 class="text-xl font-extrabold text-gray-900 dark:text-white">
                            Batch Period: {{ $batch->start_date->format('F d, Y') }} to {{ $batch->end_date->format('F d, Y') }}
                        </h2>
                        <p class="text-xs text-gray-500 mt-1">
                            Generated by <strong>{{ $batch->generatedBy->name }}</strong> on {{ $batch->created_at->format('M d, Y h:i A') }}
                        </p>
                    </div>
                    <div class="flex items-center gap-3">
                        <x-filament::badge
                            color="{{ $batch->status === 'draft' ? 'warning' : ($batch->status === 'approved' ? 'success' : 'info') }}"
                            size="lg">
                            {{ strtoupper($batch->status) }}
                        </x-filament::badge>
                    </div>
                </div>

                <!-- Workflow States Alerts / Prompts -->
                <div>
                    @if($batch->status === 'draft')
                    <div class="bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-900/40 p-4 rounded-xl flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                        <div class="flex items-start gap-3">
                            <div class="p-2 bg-amber-100 dark:bg-amber-900/40 rounded-lg text-amber-800 dark:text-amber-300">
                                <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                                </svg>
                            </div>
                            <div>
                                <span class="font-bold text-sm text-amber-900 dark:text-amber-300">Review Gate Active</span>
                                <p class="text-xs text-amber-800 dark:text-amber-400/90 mt-0.5">
                                    This batch is in <strong>Draft</strong>. Review aggregated employee data, apply manual leaves if needed, and lock the batch. Email dispatches are strictly disabled.
                                </p>
                            </div>
                        </div>
                        <div class="flex gap-2 shrink-0">
                            <x-filament::button wire:click="approveBatch({{ $batch->id }})" color="success" icon="heroicon-m-check-badge">
                                Approve & Lock Batch
                            </x-filament::button>
                            <x-filament::button disabled color="gray" icon="heroicon-m-paper-airplane">
                                Send Timesheets
                            </x-filament::button>
                        </div>
                    </div>
                    @elseif($batch->status === 'approved')
                    <div class="bg-indigo-50 dark:bg-indigo-950/20 border border-indigo-200 dark:border-indigo-800/40 p-4 rounded-xl flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                        <div class="flex items-start gap-3">
                            <div class="p-2 bg-indigo-100 dark:bg-indigo-900/40 rounded-lg text-indigo-800 dark:text-indigo-300">
                                <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                </svg>
                            </div>
                            <div>
                                <span class="font-bold text-sm text-indigo-900 dark:text-indigo-300">Locked & Ready</span>
                                <p class="text-xs text-indigo-800 dark:text-indigo-400/90 mt-0.5">
                                    The calculations are locked. You can now distribute the timesheets as PDFs to employees via the queue.
                                </p>
                            </div>
                        </div>
                        <div class="shrink-0 flex flex-wrap gap-2">
                            <x-filament::button wire:click="sendBatchImmediately({{ $batch->id }})" color="success" icon="heroicon-m-bolt" size="lg">
                                Send Immediately (Sync)
                            </x-filament::button>
                            <x-filament::button wire:click="sendBatch({{ $batch->id }})" color="primary" icon="heroicon-m-paper-airplane" size="lg">
                                Send Bulk Timesheets via Queue
                            </x-filament::button>
                        </div>
                    </div>
                    @elseif($batch->status === 'dispatched')
                    <div class="bg-emerald-50 dark:bg-emerald-950/20 border border-emerald-200 dark:border-emerald-900/40 p-4 rounded-xl flex items-start gap-3">
                        <div class="p-2 bg-emerald-100 dark:bg-emerald-900/40 rounded-lg text-emerald-800 dark:text-emerald-300">
                            <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                            </svg>
                        </div>
                        <div>
                            <span class="font-bold text-sm text-emerald-900 dark:text-emerald-300">Dispatched & Emailed</span>
                            <p class="text-xs text-emerald-800 dark:text-emerald-400/90 mt-0.5">
                                Timesheets in this batch have been queued and dispatched to all associated employees.
                            </p>
                        </div>
                    </div>
                    @endif
                </div>
            </x-filament::section>

            <!-- Card 2: Employee Snapshots Table List -->
            <x-filament::section>
                <x-slot name="heading">
                    Employee Snapshots
                </x-slot>

                <div class="flex justify-between items-center mb-4">
                    <div class="w-72">
                        <input type="text" wire:model.live="search" placeholder="Search employees..." class="w-full text-xs rounded-lg border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-900 dark:text-white shadow-sm focus:border-indigo-500 focus:ring-indigo-500">
                    </div>
                </div>

                <div class="overflow-x-auto border border-gray-200 dark:border-gray-800 rounded-xl">
                    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                        <thead class="bg-gray-50 dark:bg-white/5 text-xs text-gray-700 dark:text-gray-300 uppercase tracking-wider">
                            <tr>
                                <th class="px-4 py-3">Employee</th>
                                <th class="px-4 py-3 text-center">Cal. Days</th>
                                <th class="px-4 py-3 text-center">Exp. Days</th>
                                <th class="px-4 py-3 text-center">Worked</th>
                                <th class="px-4 py-3 text-center">Leaves</th>
                                <th class="px-4 py-3 text-center">Holidays</th>
                                <th class="px-4 py-3 text-center">Late</th>
                                <th class="px-4 py-3 text-right">Hours</th>
                                <th class="px-4 py-3 text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-gray-200 dark:divide-gray-800">
                            @php
                            $records = $batch->records;
                            if ($search) {
                            $records = $records->filter(fn($r) => str_contains(strtolower($r->user->name), strtolower($this->search)));
                            }
                            @endphp
                            @forelse($records as $r)
                            <tr class="hover:bg-gray-50 dark:hover:bg-white/5 transition">
                                <td class="px-4 py-3 font-bold text-gray-900 dark:text-white">
                                    {{ $r->user->name }}
                                    <span class="block text-[10px] text-gray-400 font-normal">{{ $r->user->email }}</span>
                                </td>
                                <td class="px-4 py-3 text-center font-mono">{{ $r->total_calendar_days }}</td>
                                <td class="px-4 py-3 text-center font-mono">{{ $r->expected_working_days }}</td>
                                <td class="px-4 py-3 text-center font-mono text-emerald-600 dark:text-emerald-400 font-bold">{{ $r->days_worked }}</td>
                                <td class="px-4 py-3 text-center font-mono text-indigo-600 dark:text-indigo-400">{{ $r->leaves_count }}</td>
                                <td class="px-4 py-3 text-center font-mono">{{ $r->holidays_count }}</td>
                                <td class="px-4 py-3 text-center font-mono text-red-600 dark:text-red-400 font-semibold">{{ $r->late_count }}</td>
                                <td class="px-4 py-3 text-right font-bold text-gray-900 dark:text-white font-mono">{{ $r->formatted_hours }}</td>
                                <td class="px-4 py-3 text-right space-x-2 shrink-0">
                                    <button wire:click="openBreakdown({{ $r->id }})" title="Daily Breakdown" class="inline-flex p-1.5 rounded-lg bg-gray-100 hover:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700 text-gray-600 dark:text-gray-300">
                                        <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                                        </svg>
                                    </button>
                                    @if($batch->status === 'draft')
                                    <button wire:click="openLeaveModal({{ $r->user_id }})" title="Add Manual Leave" class="inline-flex p-1.5 rounded-lg bg-indigo-50 hover:bg-indigo-100 dark:bg-indigo-950/40 dark:hover:bg-indigo-950/80 text-indigo-600 dark:text-indigo-400">
                                        <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
                                        </svg>
                                    </button>
                                    @endif
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="9" class="px-4 py-8 text-center text-gray-500 text-sm">
                                    No records found for this batch.
                                </td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </x-filament::section>
            @else
            <div class="flex flex-col items-center justify-center py-24 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl">
                <svg class="w-16 h-16 text-gray-300 dark:text-gray-700 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                <h3 class="text-lg font-bold text-gray-900 dark:text-white">No Batch Selected</h3>
                <p class="text-sm text-gray-500 mt-1 max-w-md text-center">
                    Select an existing timesheet batch from the sidebar history or select a date range to generate a new ad-hoc batch.
                </p>
            </div>
            @endif
        </div>
    </div>

    <!-- Modal 1: Daily Breakdown Calendar Grid -->
    @if($this->showBreakdownModal && $this->breakdownRecord)
    @php
    $br = $this->breakdownRecord;
    @endphp
    <div class="fixed inset-0 z-50 overflow-y-auto bg-gray-900/50 dark:bg-black/60 flex items-center justify-center p-4">
        <div class="relative bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl max-w-4xl w-full shadow-2xl overflow-hidden my-auto">
            <div class="bg-gray-50 dark:bg-white/5 px-6 py-4 border-b border-gray-200 dark:border-gray-800 flex justify-between items-center">
                <div>
                    <h3 class="text-base font-bold text-gray-900 dark:text-white">Daily Status Breakdown</h3>
                    <p class="text-xs text-gray-500 mt-0.5">Employee: <strong>{{ $br->user->name }}</strong></p>
                </div>
                <button wire:click="$set('showBreakdownModal', false)" class="text-gray-400 hover:text-gray-600 dark:hover:text-white">
                    <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>

            <div class="p-6 max-h-[60vh] overflow-y-auto space-y-6 custom-modal-scrollbar">
                <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3">
                    @foreach($br->daily_breakdown_json as $date => $status)
                    <div class="p-3 rounded-xl border border-gray-100 dark:border-gray-800 bg-gray-50/50 dark:bg-white/5 flex items-center justify-between gap-3">
                        <div>
                            <span class="block text-xs font-bold text-gray-900 dark:text-white">
                                {{ \Carbon\Carbon::parse($date)->format('M d, Y') }}
                            </span>
                            <span class="block text-[10px] text-gray-500 dark:text-gray-400">
                                {{ \Carbon\Carbon::parse($date)->format('l') }}
                            </span>
                        </div>
                        <span class="inline-block px-2.5 py-1 text-[9px] font-extrabold rounded-md uppercase tracking-wider
                                    {{ $status === 'Present' ? 'bg-emerald-50 text-emerald-800 dark:bg-emerald-950/20 dark:text-emerald-400' : 
                                       ($status === 'Leave' ? 'bg-blue-50 text-blue-800 dark:bg-blue-950/20 dark:text-blue-400' : 
                                       ($status === 'Holiday' ? 'bg-gray-100 text-gray-800 dark:bg-white/5 dark:text-gray-300' : 'bg-red-50 text-red-800 dark:bg-red-950/20 dark:text-red-400')) }}">
                            {{ $status }}
                        </span>
                    </div>
                    @endforeach
                </div>

                @if(!empty($br->late_logs_json))
                <div class="border-t border-gray-100 dark:border-gray-800 pt-4">
                    <span class="text-xs font-bold text-gray-500 uppercase tracking-wider block mb-2">Late Arrival Timestamps</span>
                    <div class="grid grid-cols-1 sm:grid-cols-2 gap-2 text-[11px] font-mono text-red-600 dark:text-red-400">
                        @foreach($br->late_logs_json as $log)
                        <div>• {{ \Carbon\Carbon::parse($log)->format('M d, Y h:i A') }}</div>
                        @endforeach
                    </div>
                </div>
                @endif
            </div>

            <div class="bg-gray-50 dark:bg-white/5 px-6 py-4 border-t border-gray-200 dark:border-gray-800 text-right">
                <x-filament::button wire:click="$set('showBreakdownModal', false)" color="gray">
                    Close
                </x-filament::button>
            </div>
        </div>
    </div>
    @endif

    <!-- Modal 2: Add Manual Leave Injection -->
    @if($this->showLeaveModal)
    <div class="fixed inset-0 z-50 overflow-y-auto bg-gray-900/50 dark:bg-black/60 flex items-center justify-center p-4">
        <div class="relative bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl max-w-md w-full shadow-2xl overflow-hidden my-auto">
            <div class="bg-gray-50 dark:bg-white/5 px-6 py-4 border-b border-gray-200 dark:border-gray-800 flex justify-between items-center">
                <div>
                    <h3 class="text-base font-bold text-gray-900 dark:text-white">Add Manual Leave</h3>
                    <p class="text-xs text-gray-500 mt-0.5">Recalculates draft snapshots automatically on submit</p>
                </div>
                <button wire:click="resetLeaveForm" class="text-gray-400 hover:text-gray-600 dark:hover:text-white">
                    <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>

            <form wire:submit.prevent="addManualLeave">
                <div class="p-6 max-h-[60vh] overflow-y-auto space-y-4 custom-modal-scrollbar">
                    <div>
                        <label class="text-xs font-bold uppercase tracking-wider text-gray-500 block mb-1">Leave Type</label>
                        <select wire:model.defer="leaveType" class="w-full text-sm rounded-lg border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-900 dark:text-white shadow-sm focus:border-indigo-500 focus:ring-indigo-500" required>
                            <option value="Sick">Sick Leave</option>
                            <option value="Casual">Casual Leave</option>
                            <option value="LWP">Leave Without Pay (LWP)</option>
                            <option value="Maternity">Maternity Leave</option>
                            <option value="Paternity">Paternity Leave</option>
                        </select>
                    </div>

                    <div class="grid grid-cols-2 gap-4">
                        <div>
                            <label class="text-xs font-bold uppercase tracking-wider text-gray-500 block mb-1">Start Date</label>
                            <input type="date" wire:model.defer="leaveStartDate" class="w-full text-sm rounded-lg border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-900 dark:text-white shadow-sm focus:border-indigo-500 focus:ring-indigo-500" required>
                        </div>
                        <div>
                            <label class="text-xs font-bold uppercase tracking-wider text-gray-500 block mb-1">End Date</label>
                            <input type="date" wire:model.defer="leaveEndDate" class="w-full text-sm rounded-lg border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-900 dark:text-white shadow-sm focus:border-indigo-500 focus:ring-indigo-500" required>
                        </div>
                    </div>

                    <div>
                        <label class="text-xs font-bold uppercase tracking-wider text-gray-500 block mb-1">Reason (Optional)</label>
                        <textarea wire:model.defer="leaveReason" rows="3" class="w-full text-sm rounded-lg border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-900 dark:text-white shadow-sm focus:border-indigo-500 focus:ring-indigo-500"></textarea>
                    </div>
                </div>

                <div class="px-6 py-4 bg-gray-50 dark:bg-white/5 border-t border-gray-100 dark:border-gray-800 flex justify-end gap-2">
                    <x-filament::button type="button" color="gray" wire:click="resetLeaveForm">
                        Cancel
                    </x-filament::button>
                    <x-filament::button type="submit" color="primary">
                        Register Leave
                    </x-filament::button>
                </div>
            </form>
        </div>
    </div>
    @endif

    <style>
        /* Highly visible custom scrollbars that are accessible on all operating systems */
        .custom-modal-scrollbar {
            scrollbar-width: thin;
            scrollbar-color: #a1a1aa rgba(0, 0, 0, 0.05);
        }

        .custom-modal-scrollbar::-webkit-scrollbar {
            width: 8px;
            height: 8px;
            display: block !important;
        }

        .custom-modal-scrollbar::-webkit-scrollbar-track {
            background: rgba(0, 0, 0, 0.05);
            border-radius: 9999px;
        }

        .custom-modal-scrollbar::-webkit-scrollbar-thumb {
            background-color: #a1a1aa !important;
            border-radius: 9999px;
            border: 2px solid transparent;
            background-clip: padding-box;
        }

        .custom-modal-scrollbar::-webkit-scrollbar-thumb:hover {
            background-color: #71717a !important;
        }
    </style>
</x-filament-panels::page>